### ISSUE TITLE
QGIS 2.14, buitinerror

### ISSUE THREAD

**Issue by rduivenvoorde** [NationalSecurityAgency/qgis-latlontools-plugin#2]
Hi,

trying to install the plugin in qgis 2.14.1 here, I get the following error:

![builtinerror](https://cloud.githubusercontent.com/assets/731673/24760207/4623114e-1ae8-11e7-9016-3ae48d5383f5.PNG)

will try on other systems/versions too

**Comment by hamiltoncj** [comment]
It appears that the latest version of the Boundless mgrs.py code is causing this problem. I am going to revert to an earlier version which seems to work fine. I assume you must be on Linux because the plugin works fine on Windows. I didn't see the problem until I tried my Linux VM. Keep your eyes open for an update. I will update it today and they usually approve it by the following day.

Thanks for pointing this out.

**Comment by rduivenvoorde** [comment]
@hamiltoncj nope, the problem appeared on a Windows 7 client running the 2.14.1 LTR version.
But now you ask :-) Yes, I'm actually a linux user, and just tried... same problem Running 2.14.13 on Linux here:

![workspace 2_094](https://cloud.githubusercontent.com/assets/731673/24771872/93e0b040-1b0f-11e7-9af0-68ccc8143649.png)

**Comment by hamiltoncj** [comment]
I have updated the QGIS plugin repo with a new version that should work for you. The new version will be 0.7.1. If you know how to manually install it, you can find it here:

http://plugins.qgis.org/plugins/latlontools/version/0.7.1/

Otherwise, wait until sometime tomorrow and it should be updated in the repo.

**Comment by makkau** [comment]
![broken_lat_lon](https://cloud.githubusercontent.com/assets/23531099/24805957/ac72b3cc-1b89-11e7-81b3-78bf7af23b3c.JPG)

**Comment by hamiltoncj** [comment]
Unfortunately, the QGIS team has not yet approved 0.7.1 yet so that is why you are not seeing it. I have no control on when they will approve it. Usually they are fairly quick, but it is not there yet. It probably depends on how busy they are. In your snapshot you will notice that it is still listing version 0.7. You can manually install it by downloading it from

http://plugins.qgis.org/plugins/latlontools/version/0.7.1/

Unzip the file and you will see a folder named latlontools. On Windows 7, move that folder to the following location.

C:\Users\<Your User Name>\.qgs2\python\plugins

Notice that you need to insert your user name in the above. Once you do this restart QGIS. You may need to go into "Plugins->Manage and Install Plugins..." to enable it.

**Comment by rduivenvoorde** [comment]
@hamiltoncj just checked, works :-)

One thing to add, is some examples of DMS strings that are handled. I have some issues finding out how exactly you want my DMS strings to look like (some examples strings?)

**Comment by makkau** [comment]
thank you! I will try to install separetely

* Cláudia Oliveira | arquiteta*
www.melhorlugar.blogspot.com

2017-04-07 12:34 GMT-03:00 C Hamilton <notifications@github.com>:

**Comment by hamiltoncj** [comment]
@rduivenvoorde 
I will add some DMS examples. Basically I support two formats

d m s.ss [NS] d m s.ss [EW] with degree, minute, second symbols

ddmmss.ss [NS] dddmmss.ss [EW] In this case, there must be the proper number of digits to make up the coordinate.

Given DMS coordinates I have seen I probable should also support [NS}d m s, [EW] d m s. Is there a format that you think I should support?

For some reason QGIS never approved 0.7.1 and I am thinking it was somehow lost in their e-mail. I could delete it and try again, but I have more updates to push out so assuming installing it manually works I am just going to update with the 0.8 release in the next few days.

**Comment by rduivenvoorde** [comment]
@hamiltoncj I approved it now

**Comment by rduivenvoorde** [comment]
Fixed, so will close this one
