### ISSUE TITLE
[FEATURE REQEST] add Button for Multi-Location Zoom

### ISSUE THREAD

**Issue by rduivenvoorde** [NationalSecurityAgency/qgis-latlontools-plugin#3]
Thinking out loud here: working with a user who needs to add a couple of coordinates (being some sensor positions, or cars having sensor onboard).

He can add these via the Multi-Location Zoom, but to VIEW them (let's say those 5 points) I have to popup the dialog again and click the Coordinates one by one (NOTE: you can do a multiple selection in that table, but that does not show multiple coordinates).

So some idea's:
- make it possible to 'show all'
- make it possible to 'show and keep showing' or something like that
- in the multilocation zoom, instead of the full cross-hair, show mini-crosshairs (having 4 coordinates with their full horizontal and vertical lines showing will easily become a mess)

One bigger feature request (especially working with a handfull of locations): would be cool to 'freeze' locations to a set of points in a memory layer, that is: create a memory layer (epsg:4326 + OTF?) and create points. It would even be ubercool to have at least one attribute added to the points so it is possible to visualize/categorize those points based on the value in that attribute (practical example: these points can be fixed sensor masts or driving sensor cars).

Happy to split this up in several requests, or try to do this myself and do Pull Requests>

Interested?

**Comment by hamiltoncj** [comment]
@rduivenvoorde Those are great ideas. I believe all of these changes are for the Multi-Location Zoom. Is that correct? Let me see if I can summarize how this should operate and let me know if I have it correct.

1. Use mini-crosshairs for when the coordinates are clicked on. These should be persistent as long as the coordinate is highlighted. When multiple coordinates are selected show all that are selected. These probably should only be visible as long at the Multi-Location Zoom dialog is displayed.

2. Should a "Show all" check box be added so that all points in the Multi-Location Zoom will be displayed without having to select them?

3. Should the points in the Multi-Location Zoom only be displayed as long as the dialog is displayed? This is probably how I would do unless there are reasons to do otherwise.

4. Right now when you select a coordinate it zooms to that location as well as highlights it. How should this work with multiple coordinates selected? The possibilities are 1) zoom to the last selected (this is the easiest because it already works that way), 2) don't zoom when more than 1 is selected, 3) zoom to the centroid of the coordinates and make sure all are visible. What are your thoughts?

5. Add an additional field such as "Label" or "ID". This field would be editable in the table. It will still accept just a coordinate such as 'Latitude,Longitude' but also 'Label,Latitude,Longitude'. I would check for whether there are 1 or 2 commas. Do you have a preference on what it is called? Off the top of my head my first choice is 'Label'.

6. Add a 'Make Layer' button. Is there a better name for that? This would take all the points including the label and create a memory layer. Should this layer be automatically styled or just let it received a default styling? I think I would choose a default styling.

7. Add a save list button. This is something I have been meaning to do but just have not gotten around to it.

Did I capture all your ideas in this list? Is there something more? Was there anything I misunderstood or is there anything you would implement differently?

**Comment by hamiltoncj** [comment]
I made a number of the changes and have uploaded them to github. I added a save list button, a label/name field, a persistent crosshair, and a make layer button that creates a memory layer. I don't know if it needs a show all check box or not where you can make a layer of the points. What do you think?

If you have a chance you should be able to manually install the plugin from this latest source code. If you do, let me know what you think and what you would like changed.

Thanks!!!

**Comment by hamiltoncj** [comment]
I have added a "Display markers for all locations." I think this covers all of your requests. Let me know if something is missing. I just need to update the documentation and then will push out a new release.

**Comment by hamiltoncj** [comment]
Version 0.8.1 is now available in plugins.qgis.org.

**Comment by rduivenvoorde** [comment]
UBERcool!! 

Sorry for this belated feedback, was in Essen at Hackfest, and the these github do not come to me by email...

Just tried 0.8.2 and it works VERY nice! 
I think current version is very workable for us :-)

IF I can dream further... what about 
- having a setting in where you can choose the values of the 'Label' from a dropdown in het Multi-Location Zoom table?
- is it doable to make the MultiLocation Zoom also be a DockableWidget? I know of plugins of which this is possible.
- what about the possibiltie to add a default style to this 'memory' layer you are creating.

As said, use case: being used in emergency situations where sensor cars and static sensor drive around having different icons...

Of course this can al be done by hand... but if you think this kind of use-cases is general... well, let me dream :-)

AND: thanks for the work so far already!!!

**Comment by hamiltoncj** [comment]
I will check to see what it takes to do a drop down menu. 

Dockable is certainly doable, but the dialog is a little large and would take up a lot of space. If I can make it so that by default it is not docked then I can make that change.

What did you have in mind for a default style? I don't particularly want to dictate a style for the user and I am not sure what the best method would be for the user to define a style. Do you have any ideas for this?

**Comment by rduivenvoorde** [comment]
Well, default style; I was more thinking like a user (or admin) creates a rulebased or category style based on Label values. So the/my idea is: for example: after adding some points with a Label attribute, I create a qml or sld style for it and save it to disk (including svg/icons needed, labels to show etc) once. 
Then in the settings of your plugin I can (optionally) point to that style, and the plugin, after creating the memory layer, loads that style (if defined) for the memory layer.
In this way I call it a 'default' style, but it is up to the user how it looks like.
Is this more clear?

Dropdown is maybe too much, not sure it is easy doable...

Dockable, maybe too much too... but there are some plugins doing this.

**Comment by hamiltoncj** [comment]
Just as an update. I have made the dialog dockable.  I will look into the other issues tomorrow or early next week. It is easy to apply a .qml style to a vector layer. I just need to decided how I want to implement it.

**Comment by hamiltoncj** [comment]
I now allow the user to style the layer that is created.  Right now these changes are in github. I need to do some more testing and update the documentation before publishing it. If you give it a try, you will see a Style layer drop down menu at the bottom of the multi-zoom dialog. With "Default" selected you get a layer just as it has been in the past. With  'Labeled' selected it is the same but styles it with the Label text. With Custom selected you can select a .qml file in the Settings menu and it will use that to style the new layer points. I don't know if I will try to implement the Dropdown.

If you get a chance to test it out let me know what you think.
