### ISSUE TITLE
minor issue: not clear what file extension should be when Saving Locations

### ISSUE THREAD

**Issue by rduivenvoorde** [NationalSecurityAgency/qgis-latlontools-plugin#4]
This is a minor issue, but as a user I tried to save a list of location (multi location tools), and was presented with as 'Save Lat,Lon File' dialog, which as 'type' showed me: 'Lat,Lon File' 

![selection_102](https://cloud.githubusercontent.com/assets/731673/25796538/22512066-33da-11e7-8e0f-d2ba3976402f.png)

Which (peeking into the source code) appears a .csv or .txt file...

I would propose to just call it 'csv, txt' file in the 'type/filter dropdown', 
OR add an option in the type dropdown 'show all files'. 
As you cannot see the files if they do not have the right file extension.

**Comment by hamiltoncj** [comment]
Great suggestion. I have updated GitHub so that the open dialog appears as: "Text, CSV" on Windows it shows as "Text, CSV (*.txt *.csv)". I have also added a drop down option of "All files (*.*)". 

For the Save dialog I am using "Text CSV (*.csv)". In looking at LibreOffice that is what they call a CSV file.

I have updated this on GitHub, but I am not quite ready to do a new QGIS release.  If you can use the GitHub files, give it a try and see if this works the way you like it.

Thanks for your input.

**Comment by hamiltoncj** [comment]
I am closing this request. I think the latest version addresses this issue.
