### ISSUE TITLE
Google "Geo format"

### ISSUE THREAD

**Issue by alexmodesto73** [NationalSecurityAgency/qgis-latlontools-plugin#48]
Hi,

for the tool : 
![image](https://user-images.githubusercontent.com/34935886/89418456-5dc7d200-d730-11ea-9070-c9f00cc12301.png)

It's possible to include google geoformat ?

Exemple : 

https://goo.gl/maps/z1X5oPEM4pZUoorA8

**F2HJ+C7 Porte-de-Savoie**

![image](https://user-images.githubusercontent.com/34935886/89418396-4a1c6b80-d730-11ea-9001-24163c0a5451.png)

**Comment by hamiltoncj** [comment]
That is the Plus Codes format and Lat Lon Tools supports the full code which for this location is 8FQ8F2HJ+C8. It used to that Google would use the full code on their map pages, but now they are using a shortened version which also requires a city name. In this case the code requires the entire string "F2HJ+C8 Porte-de-Savoie". I will relook at their library to see if it has a set of cities or not. As a plugin I am limited by a maximum size that a plugin can be so it is possible that I wont be able to support these shortened plus codes because it would need a city database included.

**Comment by hamiltoncj** [comment]
@alexmodesto73  Sorry it has taken so long to get back to you on this. COVID caused other priorities.  Unfortunately, using the Plus Code (Open Location Code) on something like "F2HJ+C8 Porte-de-Savoie" requires a geocoder to decode the "Porte-de-Savoie" portion of the address which is used as an approximate location for the rest of shortened "F2HJ+C8" Plus Code. I really can't implement geocoding as a part of Lat Lon Tools so the only support I can provide is a fully implemented Plus Code such as 8FQ8F2HJ+C8.

**Comment by hamiltoncj** [comment]
Closing because it requires an external geocoder in order to implement.
