### ISSUE TITLE
UI: current active tab is not remembered during session?

### ISSUE THREAD

**Issue by rduivenvoorde** [NationalSecurityAgency/qgis-latlontools-plugin#53]
During writing a little handout and writing about using the settings for latlon tools, it appeared to me that it does not remember the latest used tab in the settings, it always opens on 'Zoom to'.

![Screenshot-20201120105638-568x275](https://user-images.githubusercontent.com/731673/99786690-161e5800-2b1f-11eb-8609-c0957d3a17e5.png)

If I just changed something in the Capture tab, and after testing want to change it back, I see that users then are editing the 'Zoom to' settings, because that is what is shown then...  And though different it is for non geo-peeps all abacadabra anyway, so they do not see the difference sometimes.

I think this is a simple fix. If I have time I can probably do it myself :-)

**Comment by rduivenvoorde** [comment]
Another thing... are most users not used to using LonLat/XY so NOT the Google YX version which is now the default when you install the plugin?

**Comment by rduivenvoorde** [comment]
Ah, wait, it is more subtle: if you use (of course) the little 'wrench' icon in the Zoom to Coordinate panel, then you open on Zoom to tab. But... that is the easiest way to open the Settings....
Anybody in favour of also adding the settings button on the main toolbar (and THERE then remember the last used tab)?
Or is this just overkill?

**Comment by hamiltoncj** [comment]
@rduivenvoorde 
Originally when Lat Lon Tools was developed it was to support coordinates for Google maps, but it has since grown to be much more so I respect your recommendation to have it launch by default with XY rather than YX. Is that best for your users?

I am also fine with adding the settings button to the main toolbar. I have contemplated doing that in the past and it can be easily done. The settings button on the zoom to and multi-zoom to tools were specifically designed to go to their appropriate settings tab.

BTW do you have any idea on how to solve issue #52 ?

**Comment by hamiltoncj** [comment]
Richard, I am going to keep the default YX, lat/lon order, but I have added the settings icon to the toolbar. I also realized that I was using two different settings icons and made them all the same. Clicking the Settings icon from the toolbar will remember which tab you were last on. I have released Lat Lon Tools 3.4.5 with this change.

**Comment by rduivenvoorde** [comment]
@hamiltoncj Thanks! Fine with me, I already put it in my handouts: "DO NOT forget to change coord order" :-)
