### ISSUE TITLE
Geopackage with id field throws "Feature xxxx for attribute update not found"

### ISSUE THREAD

**Issue by rduivenvoorde** [NationalSecurityAgency/qgis-latlontools-plugin#57]
While demonstrating (online) the lat lon plugins (latest version: 3.5.0 in latest QGIS (master/3.18)) we both on different machines/os's got the same error:

2021-02-18T18:02:53     CRITICAL    Layer cc : Feature -9223372036854775808 for attribute update not found.

![Screenshot-20210218180047-842x332](https://user-images.githubusercontent.com/731673/108393204-b9146a00-7213-11eb-8309-f213f78d9336.png)

I think/hope it is just a lat lon tools plugin, but I will also try/test it without the plugin...

To reproduce:

- empty project + lat lon tools plugin installed
- create a world layer by typing 'world' in the coordinate input in the bottom bar
- create a fresh geopackage layer: point, EPSG:4326, 3 attributes: 2 text ones: 'aa', 'bb' and 1 integer one: 'id'
- make the layer editable
- create one point using 'lat lon digitize' by giving lat,lon coordinate
- in the attr form presented, then ONLY add soemthing in either the aa or the bb field (NOTHING in 'id' and leave 'fid' on 'autogenerated'
- toggle 'editable' on your new gpkg layer
- get the error message..

Note: earlier I had this on I think 3.14 or 3.16...
I think it could have something to do with the combi of an unused 'id' field and the 'fid' field of gpkg itself?

I will also try to test it with normal digitizing: same setup but without lat lon tools.

**Comment by rduivenvoorde** [comment]
Follow up: I cannot reproduce it in QGIS itself (without Lat Lon), so I think it has something todo with maybe not rightly initializing the geopackage layer?

**Comment by hamiltoncj** [comment]
Richard,

I was able to reproduce the problem though I am not sure what is going on. I will look into it next week. I appreciate the detailed instructions on how to replicate the problem.

Thanks!

**Comment by hamiltoncj** [comment]
@rduivenvoorde 
Richard,

This goes back to an earlier problem I had with iface.openFeatureForm and having to create the feature with QgsVectorLayerUtils.createFeature. We had an earlier exchange on the developers group because of needing to use createFeature rather than the normal method of creating features. Here is the code that does this.

geom = QgsGeometry.fromPointXY(QgsPointXY(x, y))
feat = QgsVectorLayerUtils.createFeature(layer, geom, {}, layer.createExpressionContext() )
if self.iface.openFeatureForm(layer, feat):
    layer.addFeature(feat)

I don't know why it is failing with the geopackage, but I suspect it has something to do with QgsVectorLayerUtils.createFeature not initializing something correctly. This may be a QGIS bug, unless there is something more I needed to do here. This part of my code has given me a lot of trouble. Do you have any ideas?

Calvin

**Comment by hamiltoncj** [comment]
This has been fixed as of Lat Lon Tools 3.6.3.
