### ISSUE TITLE
Lat Lon Tools Plugin || Multi-location Zoom window freezes

### ISSUE THREAD

**Issue by ppoliveira** [NationalSecurityAgency/qgis-latlontools-plugin#70]
Hi.

I can't manage to use multi-location zoom window. It appears on the screen but stays completely frozen, i.e., no selection or typing is possible. Other commands are working fine, including "Zoom to Coordinate".

What can be the cause of this behavior?

I'm using QGIS 3.22.4-Bialowieza on WSL (native OS Windows 11 v22H2.

Thanks in advance!

**Comment by hamiltoncj** [comment]
I have not hand any problem with it, but I don't have a Windows 11 OS. I am busy this week, but I will inquire with others on the QGIS users group to see if anyone else has seen this happen.

**Comment by ppoliveira** [comment]
Hi!

It works fine with QGIS on Win11, the malfunction is only with QGIS running on WSL/Ubuntu.

Thanks,

POL.

**Comment by hamiltoncj** [comment]
Let me refer you to a closed ticket.

https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/issues/66

Given that this is a problem on Ubuntu this ticket may apply. It appears that in some circumstances with upgrades and changes in system software something breaks with QGIS. I don't believe that it is the Lat Lon Tools plugin, but the problem is revealed in the plugin because of QGIS library calls that are being made. I think that if you do the necessary upgrades that others have done the problem will go away.

**Comment by ppoliveira** [comment]
Thanks!

Several other plugins have the same behavior, I’ve tried some updates with no success and I’ll keep trying.

**Comment by hamiltoncj** [comment]
I'm going to close this ticket since this is an Ubuntu/QGIS configuration issue and not a Lat Lon Tools problem.
