### ISSUE TITLE
External map opened, once is enough.

### ISSUE THREAD

**Issue by AllroadsNL** [NationalSecurityAgency/qgis-latlontools-plugin#87]
Hello, I use this external map feature often.
![afbeelding](https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/assets/8817345/19cf98f2-ee39-49c5-adf7-b6b1a0c89a27)
Activate the pin. (backgfround grey).
![afbeelding](https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/assets/8817345/cd315506-cf04-4a62-a8d0-9501a356f9ef)
Go with the crosshair to the location and click mouse button.
Then the browser page shows up on the screen, after a while I go back to Qgis. Want to pan to another location, 
Hitting the mouse button to drag, gives me a new browser map. This I do not want, It is annoying me, that I forgot, that is still activated.
Then I must deactivateit  by clicking on the hand.
![afbeelding](https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/assets/8817345/d1404239-c9d0-4259-ae7f-5c5616e8b969)
Then dragging around.
I thought more people must find this annoying, therefore this issue.
I search in settings, hoped that I could set it to only use once.
This is not possible.

Could it be made like this?

**Comment by hamiltoncj** [comment]
This is the standard way almost all if not all interactive canvas tools work. Once you click on them they become active and it is not until you click on some other tool that it become inactive. I understand your dislike. I have done the same, but since I am using the QGIS map tool interface that handles all this interaction, there is not anything I can do about it. I don't want to reinvent a new interface.

**Comment by AllroadsNL** [comment]
Thanks for the comment,  Yes. it is a normal behaviour in Qgis, Hoped for else. I still use it to go from, to ...
